manga:
  villains:
    jeshtar: 1
    troll_hound: 3
  priority:
    - jeshtar
    - troll_hound
comic:
  villains:
    clown: 1
  priority:
    - clown
stars:
  villains:
    fanboy: 1
  priority:
    - fanboy
hero:
  villains:
    henchman: 1
  priority:
    - henchman
